Repository AdrianKokot/put-sorting-madness, pull requests merged in 2022-12, with the labels that each got.

#20 Setup maven workflow
  .editorconfig
  .github/workflows/javadoc.yml
  .github/workflows/maven.yml
  .github/workflows/release.yml
  .gitignore
  pom.xml
  src/test/java/pl/put/poznan/ExampleTest.java
  target/classes/application.properties
  target/classes/pl/put/poznan/transformer/app/TextTransformerApplication.class
  target/classes/pl/put/poznan/transformer/logic/TextTransformer.class
  target/classes/pl/put/poznan/transformer/rest/TextTransformerController.class
  target/maven-status/maven-compiler-plugin/compile/default-compile/createdFiles.lst
  target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst
  target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/createdFiles.lst
  target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/inputFiles.lst
Labels: documentation, feature, ci/cd

#23 Add sorting controller
  .gitignore
  src/main/java/pl/put/poznan/madness/app/SortingMadnessApplication.java
  src/main/java/pl/put/poznan/madness/logic/JavaSort.java
  src/main/java/pl/put/poznan/madness/logic/Sort.java
  src/main/java/pl/put/poznan/madness/logic/SortRunnerImpl.java
  src/main/java/pl/put/poznan/madness/logic/interfaces/ISortRunner.java
  src/main/java/pl/put/poznan/madness/logic/models/SortBenchmarkResult.java
  src/main/java/pl/put/poznan/madness/logic/models/SortPerformance.java
  src/main/java/pl/put/poznan/madness/logic/models/SortResult.java
  src/main/java/pl/put/poznan/madness/rest/SortingMadnessController.java
  src/main/java/pl/put/poznan/madness/rest/exceptions/InvalidSortInputException.java
  src/main/java/pl/put/poznan/madness/rest/exceptions/MissingPropertyKeyException.java
  src/main/java/pl/put/poznan/madness/rest/exceptions/NotAllCustomObjectHaveSortablePropertyException.java
  src/main/java/pl/put/poznan/madness/rest/models/ISortableItem.java
  src/main/java/pl/put/poznan/madness/rest/models/NumericKeySortableItem.java
  src/main/java/pl/put/poznan/madness/rest/models/SortDto.java
  src/main/java/pl/put/poznan/madness/rest/models/SortableItem.java
  src/main/java/pl/put/poznan/madness/rest/models/SortingInput.java
  src/main/java/pl/put/poznan/madness/rest/models/StringKeySortableItem.java
  src/main/java/pl/put/poznan/madness/rest/utils/SortDtoParser.java
  src/main/java/pl/put/poznan/madness/rest/utils/SortableItemSerializer.java
  src/main/resources/application.properties
Labels: feature

#27 Add Javadoc technical documentation
  src/main/java/pl/put/poznan/madness/logic/SortRunnerImpl.java
  src/main/java/pl/put/poznan/madness/logic/sorting/Sorter.java
  src/main/java/pl/put/poznan/madness/logic/sorting/strategies/boundary/AbstractSort.java
  src/main/java/pl/put/poznan/madness/rest/SortingMadnessController.java
  src/main/java/pl/put/poznan/madness/rest/utils/SortDtoParser.java
Labels: documentation

#28 Implement MergeSort
  src/main/java/pl/put/poznan/madness/logic/SortRunnerImpl.java
  src/main/java/pl/put/poznan/madness/logic/sorting/strategies/MergeSort.java
  src/main/java/pl/put/poznan/madness/logic/sorting/strategies/boundary/SortingAlgorithm.java
Labels: feature
